# Site  http://localhost/Security
title: Hacking Professional
description: Seguridad informatica, Hacking Etico, Pentesting.
url: "https://HackingProfessional.github.io/Security"
logo: logo.png                                       # Site logo
locale: es_ES.UTF-8

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/coding.jpeg             # this image will be shown on post list page
  default-post: images/wall.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-136401706-1

# Social Links
email:              gerueda6@misena.edu.co
#google.plus:        username
#twitter:            username
facebook:           Gerh002
#github:            username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          gerardo_rh97
profile:            about
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
hackthebox:         67969

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
